In [2]:
import numpy as np

In [3]:
#creation of the area 
n = 10
area_a = np.zeros((n,n))
area_b = np.zeros((n,n))
area_a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
#la pertubation
area_a[1,1] = 1
area_a[0,0] = 1
area_a[n-1, n-1] = 1
area_a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
#creation of the interior checker
def spread_function(array_x):
    '''spread 1 through X a 2d array'''
    for i1 in range(1, n-1):
        for i2 in range(1, n-1):
            #if the cell if already full
            if array_x[i1,i2] > 0:
                compteur = 0
                #we check around it
                for h1 in range(i1-1,i1+2):
                    for h2 in range(i1-1,i1+2):
                        if array_x[h1,h2]==1:
                            compteur+= 1
                #if the area is saturated the cell dies
                if compteur > 5:
                    array_x[i1,i2] = 0
            #if the cell is empty
            elif array_x[i1,i2]==0:
                compteur = 0
                #we check around it
                for h1 in range(i1-1,i1+2):
                    for h2 in range(i1-1,i1+2):
                        if array_x[h1,h2]==1:
                            compteur+= 1
                #with enough space a cell emerges
                if 1 > compteur > 5:
                      array_x[i1,i2] = 1                          
    return array_x

spread_function(area_a)
area_a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])